name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Execute publish script
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        chmod +x ./publish.sh
        ./publish.sh
